### PR TITLE
Add in SASL and Hadoop Tokens to the summary

### PR DESCRIPTION
**Pull request by joshelser**
Also fixed a syntax error in the sasl doc.

When I was trying to find some info on delegation tokens, I noticed that there was some nice content in the book, but it was unreachable. Same case for the SASL chapter.

I intentionally omitted the Services chapter as it appeared incomplete.

### CODE REVIEW

**Comment by joshelser** [comment]
Thanks, Vipin!

Just rebased this on top of master as well.

**Comment by joshelser** [comment]
@steveloughran FYI have some changes which I think would be good to land, and another one I'm going to work on today.

Any chance I could get your eyes (or really, your commit-bit ;)) when you return to a computer?

**Comment by steveloughran** [comment]
Josh I am exercising my EU duty to use up my 25 days vacation. I shall not allow the K-word to darken my thoughts until 2018. Other than that, yep, got a backlog of changes for the book

**Comment by joshelser** [comment]
No rush, Steve -- meant to be clear that I was only looking for your attention when you had the cycles to give it. I'm happy to help out in other ways if you'd like. Enjoy the well-deserved time off.

**Pull request merged**
